name: .NET API CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências
        run: dotnet restore ContactManager/ContactManager.sln

      - name: Compilar solução
        run: dotnet build ContactManager/ContactManager.sln --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test ContactManager/ContactManager.sln --verbosity normal