name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup do .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar pacotes
      run: dotnet restore ContactManager.sln

    - name: Build
      run: dotnet build ContactManager.sln --no-restore --configuration Release

    - name: Executar testes
      run: dotnet test ContactManager.sln --no-build --verbosity normal --configuration Release
